services:
  database:
    container_name: db-container
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog-tp
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  adminer:
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  database_data:


